server:
  port: 8081
  servlet:
    context-path: /boot
mybatis:
  type-aliases-package: tech.aistar.model
  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: memory
    url: jdbc:mysql://localhost:3306/jkds?useSSL=false
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp